### PR TITLE
Added an underwater effect

### PR DESCRIPTION
**Pull request by demonixis**
Hi,

This PR adds an underwater effect. I had to change the water prefab because it has only one side so I added a new reversed side as a children of the original prefab. The reversed side uses a standard material with just one transparent color. It's not the best solution, but it's OK for now.

This fixes the issue #13

### CODE REVIEW

**Comment by ColeDeanShepherd** [comment]
Nice! Unfortunately I don't have time to resolve the merge conflicts right now, I'll try to get this branch merged in later today.

**Comment by demonixis** [comment]
Hi, I have updated the branch, it must be fine now.

I have noted that the virtual reality checkbox is unchecked at each merge on this repository. What version of Unity do you use? I have switched to the stable version for the good of the project ;)

**Comment by ColeDeanShepherd** [comment]
Hmm, that's strange... I'll look into it.

I'm using Unity 5.1.4.1f1. I think the VS project files are still in the repository even though you added them to .gitignore, maybe that has something to do with it? I need to stop tracking those files.

**Comment by demonixis** [comment]
Hum... That's  caused by your Unity version. Can you update to the current release?

**Comment by demonixis** [comment]
Hum... That's  caused by your Unity version. Can you update to the current release?

**Comment by ColeDeanShepherd** [comment]
I haven't changed anything in your pull requests though, so I don't think that my Unity version is affecting it. One of your pull requests [updated the Unity version in TESUnity's settings](https://github.com/ColeDeanShepherd/TESUnity/blob/master/ProjectSettings/ProjectVersion.txt) as well...

With that said, though, I'm going to update to 5.4.1p4 (it was just released yesterday) and upgrade the project.

**Comment by ColeDeanShepherd** [comment]
I updated my version of Unity and upgraded the project. I also found out that develop was a few commits behind master. Now everything is up to date, maybe that will fix the problem.

**Comment by demonixis** [comment]
Yes that's the Unity version. In fact Unity 5.4 introduced the OpenVR support (HTC Vive) and a new system to enable VR support in Unity projects. With Unity 5.4+ all will be fixed ;)

**Pull request merged**
